server:
    port: 8081

spring:
    datasource:
        url: ${DIY_BOOK_SHELF_DS_URL}
        username: ${DIY_BOOK_SHELF_DS_USER}
        password: ${DIY_BOOK_SHELF_DS_PASS}
        driverClassName: com.mysql.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: none
            dialect: org.hibernate.dialect.MySQLDialect

logging:
    level:
        org.springframework.web: DEBUG
